INSERT INTO "transaction_type" ("name", "description") VALUES ('deposit', 'For Deposit money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('withdraw', 'For Withdraw money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('send', 'For Send money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('receive', 'For Receive money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('paybill', 'For Paybill money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('buygoods', 'For Buygoods money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('airtime', 'For Airtime money MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('fuliza', 'For Fuliza MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('airtime_for', 'For Airtime money for other phone number MPESA transactions');
INSERT INTO "transaction_type" ("name", "description") VALUES ('invalid', 'For Invalid money MPESA transactions');