name: Docker Execute
run-name: ${{github.actor}} initiated a docker image build

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build an run Docker Image
        run: |
          docker build -t app_api .
          docker run app_api


